In [1]:
## Import Libraries 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# often you will have data in a seperate file, you need to load the data
Heart = pd.read_table("Data/Heart.csv", sep = ',')
print(Heart.head())

   Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No  


In [3]:
# You can read data directly from Gihub Too
Heart = pd.read_csv("https://media.githubusercontent.com/media/Ajim63/FIN-410-Python-Codes-and-Data/main/Python%20Codes/Data/Heart.csv", index_col="Unnamed: 0")
print(Heart.head())

   Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
1   63    1       typical     145   233    1        2    150      0      2.3   
2   67    1  asymptomatic     160   286    0        2    108      1      1.5   
3   67    1  asymptomatic     120   229    0        2    129      1      2.6   
4   37    1    nonanginal     130   250    0        0    187      0      3.5   
5   41    0    nontypical     130   204    0        2    172      0      1.4   

   Slope   Ca        Thal  AHD  
1      3  0.0       fixed   No  
2      2  3.0      normal  Yes  
3      2  2.0  reversable  Yes  
4      3  0.0      normal   No  
5      1  0.0      normal   No  


In [19]:
Heart

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
1     63    1       typical     145   233    1        2    150      0   
2     67    1  asymptomatic     160   286    0        2    108      1   
3     67    1  asymptomatic     120   229    0        2    129      1   
4     37    1    nonanginal     130   250    0        0    187      0   
5     41    0    nontypical     130   204    0        2    172      0   
..   ...  ...           ...     ...   ...  ...      ...    ...    ...   
298   57    0  asymptomatic     140   241    0        0    123      1   
299   45    1       typical     110   264    0        0    132      0   
300   68    1  asymptomatic     144   193    1        0    141      0   
301   57    1  asymptomatic     130   131    0        0    115      1   
302   57    0    nontypical     130   236    0        2    174      0   

     Oldpeak  Slope   Ca        Thal  AHD  
1        2.3      3  0.0       fixed   No  
2        1.5      2  3.0      normal  Yes  
3        2.6      2  2.0  reversable  Yes  
4        3.5      3  0.0      normal   No  
5        1.4      1  0.0      normal   No  
..       ...    ...  ...         ...  ...  
298      0.2      2  0.0  reversable  Yes  
299      1.2      2  0.0  reversable  Yes  
300      3.4      2  2.0  reversable  Yes  
301      1.2      2  1.0  reversable  Yes  
302      0.0      2  1.0      normal  Yes  

[297 rows x 14 columns]

In [7]:
## Remove Missing Values

Heart.dropna(inplace =True)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
X = Heart[['Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal']]

In [10]:
X.drop(['ChestPain','Thal'], axis = 1, inplace =True)

/Users/ajimuddin/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [14]:
Y = Heart[['AHD']]

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_encoder = LabelEncoder()
#B = ['No', 'Yes']
y = label_encoder.fit_transform(Y['AHD'])

In [18]:
Y

AHD
1     No
2    Yes
3    Yes
4     No
5     No
..   ...
298  Yes
299  Yes
300  Yes
301  Yes
302  Yes

[297 rows x 1 columns]

In [17]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf = LogisticRegression(random_state=0).fit(X, y)

/Users/ajimuddin/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
prediction  =clf.predict(X[0:2])

In [36]:
prediction

array([0, 1])

In [39]:
Heart.groupby('Thal').size()

Thal
fixed          18
normal        164
reversable    115
dtype: int64

In [35]:
one_hot = pd.get_dummies(Heart['ChestPain'])
X = X.join(one_hot)

In [37]:
one_hot = pd.get_dummies(Heart['Thal'])
X = X.join(one_hot)

In [40]:
clf = LogisticRegression(random_state=0).fit(X, y)

/Users/ajimuddin/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [42]:
prediction  =clf.predict(X)

In [47]:
prediction

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [54]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [51]:
np.sum(abs(y-prediction))

36

In [52]:
len(y)

297

In [55]:
from sklearn.model_selection import train_test_split

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [83]:
clf = LogisticRegression(random_state=0).fit(X_train, y_train)

/Users/ajimuddin/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [85]:
Prediction_training = clf.predict(X_train)

In [88]:
sum(abs(y_train-Prediction_training))

18

In [89]:
len(y_train)

198

In [94]:
18/198

0.09090909090909091

In [90]:
Prediction_test = clf.predict(X_test)

In [92]:
sum(abs(y_test-Prediction_test))

23

In [93]:
len(y_test)

99

In [95]:
23/99

0.23232323232323232

In [120]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

In [121]:
scalar.fit(X_train)

StandardScaler()

In [122]:
X_train_standard = scalar.transform(X_train)

In [123]:
X_test_standard = scalar.transform(X_test)

In [105]:
X_train.describe()

Age         Sex      RestBP        Chol         Fbs     RestECG  \
count  198.000000  198.000000  198.000000  198.000000  198.000000  198.000000   
mean    54.272727    0.656566  131.262626  246.181818    0.121212    0.994949   
std      9.054621    0.476059   17.134929   55.066617    0.327201    0.994898   
min     34.000000    0.000000   94.000000  126.000000    0.000000    0.000000   
25%     47.000000    0.000000  120.000000  208.250000    0.000000    0.000000   
50%     55.500000    1.000000  130.000000  240.500000    0.000000    1.000000   
75%     60.000000    1.000000  140.000000  282.000000    0.000000    2.000000   
max     77.000000    1.000000  200.000000  564.000000    1.000000    2.000000   

            MaxHR       ExAng     Oldpeak       Slope          Ca  \
count  198.000000  198.000000  198.000000  198.000000  198.000000   
mean   148.979798    0.348485    1.054040    1.611111    0.616162   
std     23.045741    0.477698    1.116811    0.608967    0.880783   
min     88.000000    0.000000    0.000000    1.000000    0.000000   
25%    132.000000    0.000000    0.000000    1.000000    0.000000   
50%    153.000000    0.000000    0.800000    2.000000    0.000000   
75%    163.000000    1.000000    1.800000    2.000000    1.000000   
max    194.000000    1.000000    4.400000    3.000000    3.000000   

       asymptomatic  nonanginal  nontypical     typical       fixed  \
count    198.000000  198.000000  198.000000  198.000000  198.000000   
mean       0.515152    0.282828    0.141414    0.060606    0.065657   
std        0.501037    0.451515    0.349332    0.239211    0.248309   
min        0.000000    0.000000    0.000000    0.000000    0.000000   
25%        0.000000    0.000000    0.000000    0.000000    0.000000   
50%        1.000000    0.000000    0.000000    0.000000    0.000000   
75%        1.000000    1.000000    0.000000    0.000000    0.000000   
max        1.000000    1.000000    1.000000    1.000000    1.000000   

           normal  reversable  
count  198.000000  198.000000  
mean     0.545455    0.388889  
std      0.499192    0.488734  
min      0.000000    0.000000  
25%      0.000000    0.000000  
50%      1.000000    0.000000  
75%      1.000000    1.000000  
max      1.000000    1.000000

In [124]:
X_train_standard.mean(axis=0)

array([-9.86864911e-17, -1.12143740e-16, -4.23903337e-16, -9.75650537e-17,
        4.48574959e-18,  6.95291187e-17,  1.45786862e-17, -3.81288716e-17,
        1.60365548e-16, -1.79429984e-17,  1.34572488e-17,  8.97149919e-17,
        1.79429984e-17,  1.31208176e-16, -4.93432455e-17, -6.72862439e-17,
        9.86864911e-17,  8.52292423e-17])

In [111]:
X_train_standard.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [125]:
X_test_standard.mean(axis=0)

array([ 0.08947135,  0.12763069,  0.07564704,  0.06381244,  0.21664456,
        0.00508927,  0.08085212, -0.13779198,  0.00408035, -0.04157294,
        0.20695124, -0.22232432, -0.02242807,  0.20291986,  0.21166688,
       -0.06117355,  0.04057204, -0.01036005])

In [126]:
X_test_standard.std(axis=0)

array([0.99824734, 0.94844479, 1.10703512, 0.82263678, 1.20662285,
       1.00257381, 0.98671697, 0.94518928, 1.12973174, 1.04671395,
       1.17756063, 0.98186164, 0.98887168, 1.17323083, 1.31710555,
       0.8841407 , 0.99546296, 0.99758214])

In [127]:
clf = LogisticRegression(random_state=0).fit(X_train_standard, y_train)

In [128]:
Prediction_training = clf.predict(X_train_standard)

In [129]:
sum(abs(y_train-Prediction_training))

17

In [130]:
Prediction_test = clf.predict(X_test_standard)

In [131]:
sum(abs(y_test-Prediction_test))

26

In [62]:
# Drop column ChestPain as it is now encoded
Heart_2 = Heart.drop('ChestPain',axis = 1)
# Join the encoded df
Heart_2 = Heart_2.join(one_hot)

In [31]:
Heart.groupby('ChestPain').size()

ChestPain
asymptomatic    142
nonanginal       83
nontypical       49
typical          23
dtype: int64

In [21]:
one_hot

asymptomatic  nonanginal  nontypical  typical
1               0           0           0        1
2               1           0           0        0
3               1           0           0        0
4               0           1           0        0
5               0           0           1        0
..            ...         ...         ...      ...
298             1           0           0        0
299             0           0           0        1
300             1           0           0        0
301             1           0           0        0
302             0           0           1        0

[297 rows x 4 columns]

In [ ]:
### Creat Train and Test Data 

## Normalize Data